common:
  containerRegistryURL: rk8sacr.azurecr.io
  ingressClass: azure-application-gateway

  
ui:
  replicas: 2
  image:
    name: todo-ui
    tag: v1
  port: 80
  ServicePort: 80
  ingress:
    host: dev-ui.ajay-azuredevops.shop

getTask:
  replicas: 2
  image:
    name: todo-get-task
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:devdas-sql-server.database.windows.net,1433;Database=dev-01-sqldb;Uid=devops123;Pwd=Devops@1@3#5;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: dev-get-tasks-api.ajay-azuredevops.shop
    ingressClass: azure-application-gateway


deleteTask:
  replicas: 2
  image:
    name: todo-delete-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:devdas-sql-server.database.windows.net,1433;Database=dev-01-sqldb;Uid=devops123;Pwd=Devops@1@3#5;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: dev-delete-task-api.ajay-azuredevops.shop
    ingressClass: azure-application-gateway


addTask:
  replicas: 2
  image:
    name: todo-add-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:devdas-sql-server.database.windows.net,1433;Database=dev-01-sqldb;Uid=devops123;Pwd=Devops@1@3#5;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: dev-add-task-api.ajay-azuredevops.shop
    ingressClass: azure-application-gateway
